name: mango_leaf_disease
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  go_router: ^15.1.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logobig.png"
  min_sdk_android: 21 

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


